### ISSUE TITLE
aliclouldPush 1.9.8版本的podspec地址写错了

### ISSUE THREAD

**Issue by zhuiyi007** [aliyun/aliyun-specs#11]
aliclouldPush 1.9.8版本的podspec的source地址多写了一个s 应该是“https”，而不是“httpss”
s.source = { :http => "httpss://ios-repo.oss-cn-shanghai.aliyuncs.com/push/1.9.8/push.zip" }

**Comment by SducodeMonkey** [comment]
已修复，多谢反馈。
