### ISSUE TITLE
無法在Simulator build release 版本

### ISSUE THREAD

**Issue by charlie80124** [aliyun/aliyun-specs#25]
1. ld: warning: ignoring file /Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID, missing required architecture i386 in file Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID (3 slices)
2.  Undefined symbol: _OBJC_CLASS_$_UTDevice

**Comment by yannan-cr** [comment]
目前xCode11 和 MacOS 11.15 已经不支持i386架构的iOS模拟器了。我们这里后续也将不支持i386架构的framework。您这边可以也可以考虑去除i386架构的支持了。
