### ISSUE TITLE
您好，我pod下来的库在工程中运行报这个错，提示缺失的这个文件在finder中可以找到，文档中没有提到相关配置，希望您能提供帮助，谢谢！

### ISSUE THREAD

**Issue by wangxiaodan820** [aliyun/aliyun-specs#3]
![2017-05-18 11 31 49](https://cloud.githubusercontent.com/assets/13794078/26189071/5980b1fc-3bd5-11e7-856b-c1292129e9c6.png)

**Comment by SducodeMonkey** [comment]
稍等回复。

**Comment by wangxiaodan820** [comment]
好的，辛苦啦

**Comment by SducodeMonkey** [comment]
目前有同学在跟进Pods集成错误的问题，如果现在需要测试集成，建议先参考文档进行手动集成，问题解决后我ping你。

**Comment by wangxiaodan820** [comment]
好的

**Comment by SducodeMonkey** [comment]
Feedback SDK Pod仓库已更新，执行`pod repo update local_repo_name`，更新下仓库，然后再尝试集成。
[Demo](https://github.com/aliyun/alicloud-ios-demo/tree/master/feedback_ios_demo)也做了更新，可以参考下。

**Comment by SducodeMonkey** [comment]
问题有没解决？

**Comment by wangxiaodan820** [comment]
感谢您的跟进，问题已解决
